FROM jenkins/jenkins:lts-jdk11
USER root
ENV http_proxy=http://web-proxy.corp.hpecorp.net:8080
ADD requirements.txt .
RUN apt-get -o Acquire::http::proxy=${http_proxy} -qq update && \
	apt-get -o Acquire::http::proxy=${http_proxy} -qq install python3 python3-pip python3-venv net-tools telnet && \
	pip3 --proxy ${http_proxy} install -r requirements.txt
