apiVersion: "sparkoperator.hpe.com/v1beta2"
kind: SparkApplication
metadata:
  name: deltalake-spark312-ssl
spec:
  sparkConf:
    "spark.hadoop.fs.s3a.access.key": "admin"
    "spark.hadoop.fs.s3a.secret.key": "admin123"
    "spark.hadoop.fs.s3a.endpoint": "https://16.143.22.153:10021"
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.databricks.delta.schema.autoMerge.enabled": "true"
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "gcr.io/mapr-252711/spark-py-3.1.2:202202161825P150"
  imagePullPolicy: Always
  imagePullSecrets:
    - imagepull
  mainApplicationFile: s3a://deltalake-spark/code/loans-delta-lake-demo.py
  sparkVersion: "3.1.2"
  restartPolicy:
    type: Never
  driver:
    javaOptions: "-Dcom.amazonaws.sdk.disableCertChecking=true"
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.2
    # Note: If you run app in tenant namespace - change serviceAccount name to "hpe-<namespace>"
    serviceAccount: hpe-terry-mlops
  executor:
    javaOptions: "-Dcom.amazonaws.sdk.disableCertChecking=true"
    cores: 1
    coreLimit: "1200m"
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.2